apiVersion: apps.kubeblocks.io/v1alpha1
kind: ClusterDefinition
metadata:
  name: nebula
  labels:
    {{- include "nebula.labels" . | nindent 4 }}
spec:
  connectionCredential:
    username: root
    password: "$(RANDOM_PASSWD)"
    endpoint: "$(SVC_FQDN):$(SVC_PORT_tcp-nebula)"
    host: "$(SVC_FQDN)"
    port: "$(SVC_PORT_tcp-nebula)"
    accesskey: ""
    secretkey: ""
  componentDefs:
    - name: nebula-metad
      configSpecs:
        - name: nebula-metad-config
          templateRef: nebula-metad-config-template
          volumeName: conf
      scriptSpecs:
        - name: nebula-metad-scripts
          templateRef: nebula-metad-scripts-template
          volumeName: scripts
          defaultMode: 493
      workloadType: Stateful
      characterType: nebula-metad
      service:
        ports:
          - name: tcp-metad
            port: 9559
            targetPort: tcp-metad
      volumeTypes:
        - name: data
          type: data
      podSpec:
        securityContext:
          fsGroup: 1001
        containers:
          - name: nebula-metad
            volumeMounts:
              - name: data
                mountPath: /data
              - name: log
                mountPath: /log
              - name: conf
                mountPath: /conf
              - name: scripts
                mountPath: /scripts
            command:
              - /bin/bash
              - -c
              - |
                set -ex
                /scripts/nebula-metad-start.sh
            imagePullPolicy: {{default .Values.nebula.metad.image.pullPolicy "IfNotPresent"}}
            securityContext:
              runAsUser: 0
            livenessProbe:
              failureThreshold: 3
              httpGet:
                path: /healthz
                port: 9091
                scheme: HTTP
              periodSeconds: 15
              successThreshold: 1
              timeoutSeconds: 10
            readinessProbe:
              failureThreshold: 2
              httpGet:
                path: /healthz
                port: 9091
                scheme: HTTP
              initialDelaySeconds: 5
              periodSeconds: 15
              successThreshold: 1
              timeoutSeconds: 3
            startupProbe:
              failureThreshold: 18
              httpGet:
                path: /healthz
                port: 9091
                scheme: HTTP
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 3
            ports:
              - name: tcp-metad
                containerPort: 9559
              - name: tcp-metrics
                containerPort: 9091
            args:
            env:
              - name: CACHE_SIZE
                valueFrom:
                  resourceFieldRef:
                    divisor: 1Gi
                    resource: limits.memory
        serviceAccountName: default
        terminationGracePeriodSeconds: 300
        volumes:
          - emptyDir: {}
            name: log
    - name: nebula-storaged
      configSpecs:
        - name: nebula-storaged-config
          templateRef: nebula-storaged-config-template
          volumeName: conf
      scriptSpecs:
        - name: nebula-storaged-scripts
          templateRef: nebula-storaged-scripts-template
          volumeName: scripts
          defaultMode: 493
      workloadType: Stateful
      characterType: nebula-storaged
      service:
        ports:
          - name: tcp-storaged
            port: 9669
            targetPort: tcp-storaged
      volumeTypes:
        - name: data
          type: data
      podSpec:
        securityContext:
          fsGroup: 1001
        containers:
          - name: nebula-storaged
            volumeMounts:
              - name: data
                mountPath: /data
              - name: conf
                mountPath: /conf
              - name: scripts
                mountPath: /scripts
              - name: log
                mountPath: /log
            command:
              - /bin/bash
              - -c
              - |
                set -ex
                /scripts/nebula-storaged-start.sh
            imagePullPolicy: {{default .Values.nebula.storaged.image.pullPolicy "IfNotPresent"}}
            securityContext:
              runAsUser: 0
            livenessProbe:
              failureThreshold: 3
              httpGet:
                path: /healthz
                port: 9091
                scheme: HTTP
              periodSeconds: 15
              successThreshold: 1
              timeoutSeconds: 10
            readinessProbe:
              failureThreshold: 2
              httpGet:
                path: /healthz
                port: 9091
                scheme: HTTP
              initialDelaySeconds: 5
              periodSeconds: 15
              successThreshold: 1
              timeoutSeconds: 3
            startupProbe:
              failureThreshold: 18
              httpGet:
                path: /healthz
                port: 9091
                scheme: HTTP
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 3
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            ports:
              - name: tcp-storaged
                containerPort: 9669
              - name: tcp-metrics
                containerPort: 9091
            args:
            env:
              - name: CACHE_SIZE
                valueFrom:
                  resourceFieldRef:
                    divisor: 1Gi
                    resource: limits.memory
        serviceAccountName: default
        terminationGracePeriodSeconds: 300
        volumes:
          - emptyDir: {}
            name: log
    - name: nebula-graphd
      configSpecs:
        - name: nebula-graphd-config
          templateRef: nebula-graphd-config-template
          volumeName: conf
      scriptSpecs:
        - name: nebula-graphd-scripts
          templateRef: nebula-graphd-scripts-template
          volumeName: scripts
          defaultMode: 493
      workloadType: Stateful
      characterType: nebula-graphd
      service:
        ports:
          - name: tcp-graphd
            port: 9779
            targetPort: tcp-graphd
      volumeTypes:
        - name: data
          type: data
      podSpec:
        securityContext:
          fsGroup: 1001
        containers:
          - name: nebula-graphd
            imagePullPolicy: IfNotPresent
            volumeMounts:
              - name: conf
                mountPath: /conf
              - name: scripts
                mountPath: /scripts
              - name: log
                mountPath: /log
              - name: data
                mountPath: /data
            command:
              - /bin/bash
              - -c
              - |
                set -ex
                /scripts/nebula-graphd-start.sh
            imagePullPolicy: {{default .Values.nebula.graphd.image.pullPolicy "IfNotPresent"}}
            securityContext:
              runAsUser: 0
            livenessProbe:
              failureThreshold: 3
              httpGet:
                path: /healthz
                port: 9091
                scheme: HTTP
              periodSeconds: 15
              successThreshold: 1
              timeoutSeconds: 10
            readinessProbe:
              failureThreshold: 2
              httpGet:
                path: /healthz
                port: 9091
                scheme: HTTP
              initialDelaySeconds: 5
              periodSeconds: 15
              successThreshold: 1
              timeoutSeconds: 3
            startupProbe:
              failureThreshold: 18
              httpGet:
                path: /healthz
                port: 9091
                scheme: HTTP
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 3
            ports:
              - name: tcp-metad
                containerPort: 9779
              - name: tcp-metrics
                containerPort: 9091
            args:
            env:
              - name: CACHE_SIZE
                valueFrom:
                  resourceFieldRef:
                    divisor: 1Gi
                    resource: limits.memory
        serviceAccountName: default
        terminationGracePeriodSeconds: 300
        volumes:
          - emptyDir: {}
            name: log