apiVersion: apps.kubeblocks.io/v1alpha1
kind: ClusterDefinition
metadata:
  name: nebula
spec:
  connectionCredential:
    username: root
    password: "$(RANDOM_PASSWD)"
    endpoint: "$(SVC_FQDN):$(SVC_PORT_tcp-nebula)"
    host: "$(SVC_FQDN)"
    port: "$(SVC_PORT_tcp-nebula)"
    accesskey: ""
    secretkey: ""
  componentDefs:
    - name: nebula-metad
      workloadType: Stateful
      characterType: nebula-metad
      probes:
      monitor:
        builtIn: false
        exporterConfig:
          scrapePath: /metrics
          scrapePort: 9187
      logConfigs:
      service:
        ports:
          - name: tcp-nebula-metad
            port: 9559
            targetPort: tcp-nebula-metad
      volumeTypes:
        - name: data
          type: data
      podSpec:
        securityContext:
          fsGroup: 1001
        containers:
          - name: nebula-metad
            imagePullPolicy: {{default .Values.nebula.metad.image.pullPolicy "IfNotPresent"}}
            securityContext:
              runAsUser: 0
            livenessProbe:
              failureThreshold: 3
              httpGet:
                path: /healthz
                port: 9091
                scheme: HTTP
              periodSeconds: 15
              successThreshold: 1
              timeoutSeconds: 10
            readinessProbe:
              failureThreshold: 2
              httpGet:
                path: /healthz
                port: 9091
                scheme: HTTP
              initialDelaySeconds: 5
              periodSeconds: 15
              successThreshold: 1
              timeoutSeconds: 3
            startupProbe:
              failureThreshold: 18
              httpGet:
                path: /healthz
                port: 9091
                scheme: HTTP
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 3
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            dnsPolicy: ClusterFirst
            enableServiceLinks: true
            ports:
              - name: tcp-nebula-metad
                containerPort: 9559
              - name: tcp-metrics
                containerPort: 9091
            args:
            env:
              - name: CACHE_SIZE
                valueFrom:
                  resourceFieldRef:
                    divisor: 1Gi
                    resource: limits.memory
        serviceAccountName: default
        terminationGracePeriodSeconds: 300
        volumes:
          - emptyDir: {}
            name: tools
    - name: nebula-storaged
      workloadType: Stateful
      characterType: nebula-storaged
      probes:
      monitor:
        builtIn: false
        exporterConfig:
          scrapePath: /metrics
          scrapePort: 9187
      logConfigs:
      service:
        ports:
          - name: tcp-nebula-storaged
            port: 9669
            targetPort: tcp-nebula-storaged
      volumeTypes:
        - name: data
          type: data
      podSpec:
        securityContext:
          fsGroup: 1001
        containers:
          - name: nebula-storaged
            imagePullPolicy: {{default .Values.nebula.storaged.image.pullPolicy "IfNotPresent"}}
            securityContext:
              runAsUser: 0
            livenessProbe:
              failureThreshold: 3
              httpGet:
                path: /healthz
                port: 9091
                scheme: HTTP
              periodSeconds: 15
              successThreshold: 1
              timeoutSeconds: 10
            readinessProbe:
              failureThreshold: 2
              httpGet:
                path: /healthz
                port: 9091
                scheme: HTTP
              initialDelaySeconds: 5
              periodSeconds: 15
              successThreshold: 1
              timeoutSeconds: 3
            startupProbe:
              failureThreshold: 18
              httpGet:
                path: /healthz
                port: 9091
                scheme: HTTP
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 3
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            dnsPolicy: ClusterFirst
            enableServiceLinks: true
            ports:
              - name: tcp-nebula-storaged
                containerPort: 9669
              - name: tcp-metrics
                containerPort: 9091
            args:
            env:
              - name: CACHE_SIZE
                valueFrom:
                  resourceFieldRef:
                    divisor: 1Gi
                    resource: limits.memory
        serviceAccountName: default
        terminationGracePeriodSeconds: 300
        volumes:
          - emptyDir: {}
            name: tools
    - name: nebula-graphd
      workloadType: Stateful
      characterType: nebula-graphd
      probes:
      monitor:
        builtIn: false
        exporterConfig:
          scrapePath: /metrics
          scrapePort: 9187
      logConfigs:
      service:
        ports:
          - name: tcp-nebula-graphd
            port: 9779
            targetPort: tcp-nebula-graphd
      volumeTypes:
        - name: data
          type: data
      podSpec:
        securityContext:
          fsGroup: 1001
        containers:
          - name: nebula-graphd
            imagePullPolicy: {{default .Values.nebula.graphd.image.pullPolicy "IfNotPresent"}}
            securityContext:
              runAsUser: 0
            livenessProbe:
              failureThreshold: 3
              httpGet:
                path: /healthz
                port: 9091
                scheme: HTTP
              periodSeconds: 15
              successThreshold: 1
              timeoutSeconds: 10
            readinessProbe:
              failureThreshold: 2
              httpGet:
                path: /healthz
                port: 9091
                scheme: HTTP
              initialDelaySeconds: 5
              periodSeconds: 15
              successThreshold: 1
              timeoutSeconds: 3
            startupProbe:
              failureThreshold: 18
              httpGet:
                path: /healthz
                port: 9091
                scheme: HTTP
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 3
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            dnsPolicy: ClusterFirst
            enableServiceLinks: true
            ports:
              - name: tcp-nebula-metad
                containerPort: 9779
              - name: tcp-metrics
                containerPort: 9091
            args:
            env:
              - name: CACHE_SIZE
                valueFrom:
                  resourceFieldRef:
                    divisor: 1Gi
                    resource: limits.memory
        serviceAccountName: default
        terminationGracePeriodSeconds: 300
        volumes:
          - emptyDir: {}
            name: tools