terminationPolicy: Delete
nebula:
  version: v3.5.0
  imagePullPolicy: Always
  storageClassName: ""
  enablePVReclaim: false
  enableBR: false
  enableForceUpdate: false
  schedulerName: default-scheduler # nebula-scheduler
  unsatisfiableAction: ScheduleAnyway
  logRotate: { }
  reference:
    name: statefulsets.apps
    version: v1
  graphd:
    image: docker.io/vesoft/nebula-graphd:v3.5.0
    replicas: 1
    serviceType: NodePort
    env: []
    config: {}
    resources:
      requests:
        cpu: "500m"
        memory: "500Mi"
      limits:
        cpu: "1"
        memory: "500Mi"
    logStorage: "500Mi"
    podLabels: {}
    podAnnotations: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}
    readinessProbe: {}
    initContainers: []
    sidecarContainers: []
    sidecarVolumes: []
  metad:
    image: docker.io/vesoft/nebula-metad:v3.5.0
    replicas: 1
    env: []
    config: {}
    resources:
      requests:
        cpu: "500m"
        memory: "500Mi"
      limits:
        cpu: "1"
        memory: "1Gi"
    logStorage: "500Mi"
    dataStorage: "2Gi"
    licenseManagerURL: ""
    license: {}
    podLabels: {}
    podAnnotations: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}
    readinessProbe: {}
    initContainers: []
    sidecarContainers: []
    sidecarVolumes: []
  storaged:
    image: docker.io/vesoft/nebula-storaged:v3.5.0
    replicas: 1
    env: []
    config: {}
    resources:
      requests:
        cpu: "500m"
        memory: "500Mi"
      limits:
        cpu: "1"
        memory: "1Gi"
    logStorage: "500Mi"
    dataStorage: "10Gi"
    enableAutoBalance: false
    podLabels: {}
    podAnnotations: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}
    readinessProbe: {}
    initContainers: []
    sidecarContainers: []
    sidecarVolumes: []


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""