nebula:
  version: v3.5.0
  imagePullPolicy: IfNotPresent
  storageClassName: ""
  enablePVReclaim: false
  enableBR: false
  enableForceUpdate: false
  schedulerName: default-scheduler # nebula-scheduler
  unsatisfiableAction: ScheduleAnyway
  logRotate: { }
  reference:
    name: statefulsets.apps
    version: v1
  graphd:
    image:
      registry: docker.io
      repository: vesoft/nebula-graphd
      tag: v3.5.0
      pullPolicy: IfNotPresent
    version: v3.5.0
    replicas: 1
    serviceType: NodePort
    env: []
    config: {}
    resources:
      requests:
        cpu: "500m"
        memory: "500Mi"
      limits:
        cpu: "1"
        memory: "500Mi"
    logStorage: "500Mi"
    podLabels: {}
    podAnnotations: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}
    readinessProbe: {}
    initContainers: []
    sidecarContainers: []
    sidecarVolumes: []

  metad:
    image:
      registry: docker.io
      repository: vesoft/nebula-metad
      tag: v3.5.0
      pullPolicy: IfNotPresent
    version: v3.5.0
    replicas: 3
    env: []
    config: {}
    resources:
      requests:
        cpu: "500m"
        memory: "500Mi"
      limits:
        cpu: "1"
        memory: "1Gi"
    logStorage: "500Mi"
    dataStorage: "2Gi"
    podLabels: {}
    podAnnotations: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}
    readinessProbe: {}
    initContainers: []
    sidecarContainers: []
    sidecarVolumes: []

  storaged:
    image:
      registry: docker.io
      repository: vesoft/nebula-storaged
      tag: v3.5.0
      pullPolicy: IfNotPresent
    version: v3.5.0
    replicas: 3
    env: []
    config: {}
    resources:
      requests:
        cpu: "500m"
        memory: "500Mi"
      limits:
        cpu: "1"
        memory: "1Gi"
    logStorage: "500Mi"
    dataStorage: "10Gi"
    enableAutoBalance: false
    podLabels: {}
    podAnnotations: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}
    readinessProbe: {}
    initContainers: []
    sidecarContainers: []
    sidecarVolumes: []

  exporter:
    image: 
      registry: docker.io
      repository: vesoft/nebula-stats-exporter
      tag: v3.3.0
      pullPolicy: IfNotPresent
    version: v3.3.0
    replicas: 1
    env: [ ]
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"
    podLabels: { }
    podAnnotations: { }
    nodeSelector: { }
    tolerations: [ ]
    affinity: { }
    livenessProbe: { }


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
